## tweetfeed configuration file
##
# User's configuration
hashtags: hadoop, cloudera, hbase
outfile: tweetfeed.xml

## Don't change any settings below this line -> _______ #
loglevel: 0
last_id: 168708216706973696
